import { Activity, Archive, Download, Link2, Play, ShieldAlert, UserRoundCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import {
  attachIncidentChangeSet, closeIncident, exportIncident, handoffIncident, listIncidents,
  refreshIncident, runIncident,
} from "../../lib/tauri/agentic";
import type { Incident, IncidentAuditExport, OperationsPack } from "../../types/agentic";
import type { AgentSessionOption } from "./AgenticWorkspaceView";

type Props = { sessions: AgentSessionOption[]; activeSessionId: string | null; onOpenChanges: () => void };

export default function IncidentWorkspace({ sessions, activeSessionId, onOpenChanges }: Props) {
  const { t } = useTranslation();
  const [pack, setPack] = useState<OperationsPack>("website");
  const [selected, setSelected] = useState<string[]>(activeSessionId ? [activeSessionId] : []);
  const [symptom, setSymptom] = useState(""); const [host, setHost] = useState(""); const [port, setPort] = useState(""); const [url, setUrl] = useState("");
  const [upstreamHost, setUpstreamHost] = useState(""); const [upstreamPort, setUpstreamPort] = useState("");
  const [service, setService] = useState(""); const [container, setContainer] = useState(""); const [configPath, setConfigPath] = useState(""); const [dependencies, setDependencies] = useState("");
  const [incident, setIncident] = useState<Incident | null>(null); const [history, setHistory] = useState<Incident[]>([]); const [auditExport, setAuditExport] = useState<IncidentAuditExport | null>(null);
  const [busy, setBusy] = useState(false); const [failed, setFailed] = useState(false);
  const [changeKind, setChangeKind] = useState<"single" | "fleet">("single"); const [changeId, setChangeId] = useState(""); const [changeVersion, setChangeVersion] = useState("1");
  const [owner, setOwner] = useState(""); const [operatorSummary, setOperatorSummary] = useState(""); const [closureCode, setClosureCode] = useState<"resolved" | "accepted-risk" | "false-positive">("resolved");

  const reloadHistory = () => listIncidents().then(setHistory).catch(() => setFailed(true));
  useEffect(() => { void reloadHistory(); }, []);
  useEffect(() => { if (activeSessionId) setSelected((current) => current.includes(activeSessionId) ? current : [activeSessionId]); }, [activeSessionId]);
  const update = async (operation: () => Promise<Incident>) => { try { const next = await operation(); setIncident(next); void reloadHistory(); } catch { setFailed(true); } };
  const execute = async () => {
    if (!symptom.trim() || selected.length === 0) return;
    setBusy(true); setFailed(false); setIncident(null); setAuditExport(null);
    try {
      const next = await runIncident({ id: crypto.randomUUID(), pack, severity: "sev2", targets: selected, symptoms: [symptom.trim()], host: host.trim() || null, port: port ? Number(port) : null, url: url.trim() || null, service: service.trim() || null, container: container.trim() || null, configPath: configPath.trim() || null, upstreamHost: upstreamHost.trim() || null, upstreamPort: upstreamPort ? Number(upstreamPort) : null, dependencies: dependencies.split(",").map((item) => item.trim()).filter(Boolean) });
      setIncident(next); void reloadHistory();
    } catch { setFailed(true); } finally { setBusy(false); }
  };
  return <div className="grid gap-4">
    {failed && <p className="rounded border border-red-500/30 bg-red-500/5 p-3 text-sm text-red-500">{t("incident.error")}</p>}
    <section className="grid gap-3 rounded-lg border p-4"><h3 className="font-medium">{t("incident.history")}</h3><select className="h-9 rounded border bg-transparent px-2" value={incident?.id ?? ""} onChange={(event) => { setIncident(history.find((item) => item.id === event.target.value) ?? null); setAuditExport(null); }}><option value="">{t("incident.history.none")}</option>{history.map((item) => <option key={item.id} value={item.id}>{t(`incident.pack.${item.pack}`)} · {t(`incident.status.${item.status}`)} · {item.id}</option>)}</select></section>
    <section className="grid gap-4 rounded-lg border bg-[hsl(var(--surface))] p-4 lg:grid-cols-2">
      <div><h3 className="font-medium">{t("incident.targets")}</h3><div className="mt-2 grid gap-2">{sessions.map((item) => <label key={item.sessionId} className="flex items-center gap-2 rounded border p-2 text-sm"><input type="checkbox" checked={selected.includes(item.sessionId)} onChange={(event) => setSelected((current) => event.target.checked ? [...new Set([...current, item.sessionId])].slice(0, 10) : current.filter((id) => id !== item.sessionId))} />{item.label}</label>)}</div></div>
      <div className="grid gap-3"><label className="grid gap-1 text-sm"><span>{t("incident.pack")}</span><select className="h-9 rounded border bg-transparent px-2" value={pack} onChange={(event) => setPack(event.target.value as OperationsPack)}>{(["website","nginx","docker","disk","service"] as OperationsPack[]).map((value) => <option key={value} value={value}>{t(`incident.pack.${value}`)}</option>)}</select></label>
        <Field label={t("incident.symptoms")} value={symptom} onChange={setSymptom}/>
        {(pack === "website" || pack === "nginx" || pack === "service") && <><Field label={t("incident.host")} value={host} onChange={setHost}/><Field label={t("incident.port")} value={port} onChange={setPort}/></>}
        {(pack === "website" || pack === "nginx") && <Field label={t("incident.url")} value={url} onChange={setUrl}/>} {pack === "website" && <><Field label={t("incident.upstreamHost")} value={upstreamHost} onChange={setUpstreamHost}/><Field label={t("incident.upstreamPort")} value={upstreamPort} onChange={setUpstreamPort}/></>}
        {(pack === "website" || pack === "service") && <Field label={t("incident.service")} value={service} onChange={setService}/>} {pack === "docker" && <Field label={t("incident.container")} value={container} onChange={setContainer}/>} {(pack === "nginx" || pack === "docker" || pack === "service") && <Field label={t("incident.configPath")} value={configPath} onChange={setConfigPath}/>} {pack === "service" && <Field label={t("incident.dependencies")} value={dependencies} onChange={setDependencies}/>}<Button disabled={busy || !symptom.trim() || selected.length === 0} onClick={() => void execute()}><Play size={15}/>{t("incident.investigate")}</Button>
      </div>
    </section>
    {incident && <IncidentPresentation incident={incident} auditExport={auditExport} onOpenChanges={onOpenChanges} onAttach={() => update(() => attachIncidentChangeSet(incident.id, { kind: changeKind, id: changeId, version: Number(changeVersion), exactTargetIds: incident.targets }))} onRefresh={() => update(() => refreshIncident(incident.id))} changeKind={changeKind} setChangeKind={setChangeKind} changeId={changeId} setChangeId={setChangeId} changeVersion={changeVersion} setChangeVersion={setChangeVersion} owner={owner} setOwner={setOwner} operatorSummary={operatorSummary} setOperatorSummary={setOperatorSummary} closureCode={closureCode} setClosureCode={setClosureCode} onHandoff={() => update(() => handoffIncident(incident.id, owner, operatorSummary))} onClose={() => update(() => closeIncident(incident.id, closureCode, operatorSummary))} onExport={() => exportIncident(incident.id).then(setAuditExport).catch(() => setFailed(true))}/>} 
  </div>;
}

type PresentationProps = { incident: Incident; auditExport: IncidentAuditExport | null; onOpenChanges: () => void; onAttach: () => void; onRefresh: () => void; changeKind: "single" | "fleet"; setChangeKind: (value: "single" | "fleet") => void; changeId: string; setChangeId: (value: string) => void; changeVersion: string; setChangeVersion: (value: string) => void; owner: string; setOwner: (value: string) => void; operatorSummary: string; setOperatorSummary: (value: string) => void; closureCode: "resolved" | "accepted-risk" | "false-positive"; setClosureCode: (value: "resolved" | "accepted-risk" | "false-positive") => void; onHandoff: () => void; onClose: () => void; onExport: () => void };

function IncidentPresentation(props: PresentationProps) {
  const { t } = useTranslation(); const { incident } = props;
  return <>
    {incident.recoveryState === "metadata-only" && <p className="rounded border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-500">{t("incident.metadataOnly")}</p>}
    <section className="grid gap-3 rounded-lg border p-4"><h3 className="flex items-center gap-2 font-medium"><Activity size={17}/>{t("incident.timeline")}</h3>{incident.timeline.map((item, index) => <div key={`${item.code}-${index}`} className="flex gap-3 text-sm"><span className="text-[hsl(var(--muted))]">{index + 1}</span><span>{t(`incident.timeline.${item.code}`)}</span><span className="ml-auto text-[hsl(var(--muted))]">{t(`incident.status.${item.status}`)}</span></div>)}</section>
    <section className="grid gap-3 rounded-lg border p-4"><h3 className="font-medium">{t("incident.evidence")}</h3>{incident.evidence.length > 0 ? incident.evidence.map((item) => <details key={item.id} className="rounded border p-3 text-sm"><summary className="cursor-pointer"><span className={item.result.success ? "text-green-500" : "text-red-500"}>{item.result.success ? "✓" : "×"}</span> {item.source} · {item.targetId}</summary><pre className="mt-2 max-h-64 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(item.result.data ?? { errorCode: item.result.errorCode }, null, 2)}</pre></details>) : incident.evidenceReferences.map((item) => <p key={item.id} className="rounded border p-3 text-sm">{item.success ? "✓" : "×"} {item.source} · {item.targetId}</p>)}</section>
    {incident.comparisons.length > 0 && <section className="grid gap-3 rounded-lg border p-4"><h3 className="font-medium">{t("incident.comparison")}</h3>{incident.comparisons.map((item) => <div key={item.dimension} className="rounded border p-3 text-sm"><p className="font-medium">{item.dimension} · {t(item.drift ? "incident.drift" : "incident.consistent")}</p>{item.values.map((value) => <p key={value.targetId} className="text-[hsl(var(--muted))]">{value.targetId}: {value.signal}</p>)}</div>)}</section>}
    <section className="grid gap-2 rounded-lg border p-4"><h3 className="flex items-center gap-2 font-medium"><ShieldAlert size={17}/>{t("incident.rootCause")}</h3><p>{t(`incident.cause.${incident.rootCause.code}`)}</p><p className="text-sm text-[hsl(var(--muted))]">{t("incident.confidence", { value: Math.round(incident.rootCause.confidence * 100), count: incident.rootCause.evidenceIds.length })}</p></section>
    <section className="grid gap-3 rounded-lg border p-4"><h3 className="font-medium">{t("incident.repairPlan")}</h3><p className="text-sm">{t(`incident.fix.${incident.proposedFix.code}`)}</p><ol className="grid gap-1 text-sm">{incident.proposedFix.actionCodes.map((code, index) => <li key={code}>{index + 1}. {t(`incident.action.${code}`)}</li>)}</ol>{incident.proposedFix.dangerousDeletionBlocked && <p className="rounded border border-amber-500/30 bg-amber-500/5 p-2 text-sm text-amber-500">{t("incident.deletionBlocked")}</p>}<p className="text-xs text-[hsl(var(--muted))]">{incident.proposedFix.executionPipeline.join(" → ")}</p><Button variant="secondary" onClick={props.onOpenChanges}>{t("incident.openChanges")}</Button></section>
    <section className="grid gap-3 rounded-lg border p-4"><h3 className="flex items-center gap-2 font-medium"><Link2 size={17}/>{t("incident.changeSet")}</h3>{incident.changeSet ? <div className="flex flex-wrap items-center gap-2"><p className="text-sm">{incident.changeSet.kind} · {incident.changeSet.id} · v{incident.changeSet.version}</p><Button size="sm" variant="secondary" onClick={props.onRefresh}>{t("common.refresh")}</Button></div> : <div className="grid gap-2 md:grid-cols-[140px_1fr_100px_auto]"><select className="h-9 rounded border bg-transparent px-2" value={props.changeKind} onChange={(event) => props.setChangeKind(event.target.value as "single"|"fleet")}><option value="single">{t("incident.single")}</option><option value="fleet">{t("incident.fleet")}</option></select><Input value={props.changeId} onChange={(event) => props.setChangeId(event.target.value)} placeholder={t("incident.changeSetId")}/><Input value={props.changeVersion} onChange={(event) => props.setChangeVersion(event.target.value)}/><Button onClick={props.onAttach}>{t("incident.bind")}</Button></div>}<p className="text-sm text-[hsl(var(--muted))]">{t("incident.verification")}: {incident.verification.statusCode}</p></section>
    <section className="grid gap-3 rounded-lg border p-4"><h3 className="flex items-center gap-2 font-medium"><UserRoundCheck size={17}/>{t("incident.operations")}</h3><div className="grid gap-2 md:grid-cols-2"><Field label={t("incident.owner")} value={props.owner} onChange={props.setOwner}/><Field label={t("incident.operatorSummary")} value={props.operatorSummary} onChange={props.setOperatorSummary}/></div><div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={!props.owner.trim() || !props.operatorSummary.trim()} onClick={props.onHandoff}><UserRoundCheck size={15}/>{t("incident.handoff")}</Button><select className="h-9 rounded border bg-transparent px-2" value={props.closureCode} onChange={(event) => props.setClosureCode(event.target.value as typeof props.closureCode)}><option value="resolved">{t("incident.closure.resolved")}</option><option value="accepted-risk">{t("incident.closure.accepted-risk")}</option><option value="false-positive">{t("incident.closure.false-positive")}</option></select><Button variant="secondary" disabled={!props.operatorSummary.trim()} onClick={props.onClose}><Archive size={15}/>{t("incident.close")}</Button><Button variant="secondary" onClick={props.onExport}><Download size={15}/>{t("incident.export")}</Button></div>{incident.handoff && <p className="text-sm text-[hsl(var(--muted))]">{t("incident.handoffOwner", { owner: incident.handoff.owner })}</p>}{props.auditExport && <pre className="max-h-80 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(props.auditExport, null, 2)}</pre>}</section>
  </>;
}

function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="grid gap-1 text-sm"><span>{label}</span><Input value={value} onChange={(event) => onChange(event.target.value)}/></label>; }
