STOP REPLICA;
CHANGE REPLICATION SOURCE TO
  SOURCE_HOST = 'mysql-source',
  SOURCE_PORT = 3306,
  SOURCE_USER = 'runory_repl',
  SOURCE_PASSWORD = 'runory-replication-test-only',
  SOURCE_AUTO_POSITION = 1,
  GET_SOURCE_PUBLIC_KEY = 1;
START REPLICA;
SET PERSIST read_only = ON;
SET PERSIST super_read_only = ON;
