import type { Locale } from "./i18n";

const zh = {
  meta: { title: "Runory — 你的服务器，尽在掌握", description: "在一个本地优先的工作区，连接 SSH、管理文件、查看服务、完成部署，与逐条审批的 AI 协作。探索 Runory 桌面客户端。" },
  nav: { label: "主导航", product: "产品", workflow: "AI 协作", security: "安全", pricing: "价格", faq: "常见问题", signIn: "登录", download: "获取 Runory", menu: "打开导航", close: "关闭导航", language: "English", skip: "跳转到主要内容" },
  hero: { badge: "为每天与服务器打交道的人而造", title: "你的服务器。", accent: "尽在掌握。", description: "从第一条 SSH 命令，到文件、服务与部署。\n把远程工作的每一步，放进一个清晰、顺手的工作区。", primary: "获取 Runory", secondary: "探索工作区", note: "本地优先", note2: "无需账号即可连接", note3: "每条 AI 命令，由你决定" },
  demo: { label: "工作区交互演示", caption: "交互演示 · 示例数据，不连接真实服务器", sidebar: "服务器", group: "生产环境", connected: "已连接", secure: "SSH 加密连接", tabs: ["终端", "文件", "监控", "部署"], detail: "会话详情", host: "主机", auth: "认证方式", key: "私钥", session: "连接状态", files: "远程文件", name: "名称", size: "大小", modified: "修改时间", queue: "传输队列", transferred: "传输完成", dashboard: "服务器概览", agentless: "通过 SSH 获取，无需安装监控 Agent", metrics: ["CPU 使用率", "内存使用率", "磁盘使用率"], services: "服务状态", running: "运行中", deployments: "部署记录", deploymentName: "API 应用", deployed: "部署完成", deploymentSteps: ["拉取代码", "检查环境", "执行构建", "启动服务"], deployNote: "查看每次部署的阶段与结果，定位问题更直接。", hint: "切换标签，探索同一个连接里的不同工作方式。", context: "连接、文件与状态，始终在同一处。" },
  strip: { title: "熟悉的工具。连贯的体验。", items: ["SSH / SFTP", "Docker / PM2", "Nginx / SSL", "Git / Cron", "Windows / macOS / Linux"] },
  features: { eyebrow: "一个工作区，贯穿日常运维", title: "少一点来回切换。\n多一点从容掌控。", description: "终端之外，你需要的上下文也在手边。", items: [
    { title: "连接，自有章法", description: "分组整理主机，快速搜索与切换。多标签 SSH 会话，让生产、预发和开发环境各就各位。", tags: ["主机分组", "多会话", "密钥认证"] },
    { title: "文件，就在终端旁", description: "浏览远程目录，上传、下载、重命名与管理文件。传输队列清晰可见，无需再开一个客户端。", tags: ["SFTP", "目录导航", "传输队列"] },
    { title: "服务器状态，一眼看清", description: "查看 CPU、内存与磁盘状态，在服务和日志之间直接排查。通过 SSH 工作，无需额外部署 Agent。", tags: ["Dashboard", "服务状态", "日志查看"] },
    { title: "常用服务，集中管理", description: "把 Docker、PM2 与 Nginx 的日常操作放在同一处。理解当前状态，再确认下一步操作。", tags: ["Docker", "PM2", "Nginx"] },
    { title: "从代码到运行", description: "围绕 Git 部署组织环境变量、SSL、备份与定时任务。保留部署历史，让每一次发布都有迹可循。", tags: ["Git 部署", "SSL", "备份 / Cron"] },
    { title: "习惯，不必重新培养", description: "保留熟悉的终端输入、搜索和复制粘贴。中英双语、深浅主题，让工作区适应你的工作方式。", tags: ["中文 / English", "深浅主题", "终端搜索"] },
  ] },
  agent: { eyebrow: "AI 协作，控制权在你", title: "一起找到答案。\n每一步，由你确认。", description: "描述问题，查看建议，批准下一条命令。AI 根据真实执行结果继续分析，让排查有依据，让操作有边界。", points: ["执行前原样展示命令与风险", "每条命令都需要 Run / Cancel 审批", "写入之后，还要验证结果才能结束"], label: "AI 协作流程示意", question: "帮我检查 Nginx 为什么没有响应", steps: ["提出建议", "确认命令", "检查结果"], summaries: ["先检查 Nginx 服务状态，获取排查依据。", "在客户端确认这条只读命令，再交给终端执行。", "AI 读取脱敏结果，继续分析或提出下一条待审批命令。"], command: "systemctl status nginx --no-pager", risk: "只读 · 待你审批", result: "结果 → 分析 → 下一条建议", note: "此处仅展示流程，不执行命令。", runtime: "你定方向，AI 协助排查" },
  security: { eyebrow: "信任来自清晰的边界", title: "连接你的服务器。\n守住你的数据。", description: "本地优先是产品的起点。凭据、连接和操作权限，都有明确的归属。", items: [
    { title: "凭据留在本地保险库", description: "密码、Passphrase 与私钥由 Credential Vault 管理，不写入主机资料，也不进入云同步。" },
    { title: "认真对待每一次连接", description: "未知主机需要你显式信任；主机密钥发生变化时，连接会被阻止。" },
    { title: "操作可以审查", description: "AI 命令先审批再执行。结构化修复使用变更集与结果验证，仅在支持时提供真实回滚。" },
  ], local: "你的设备", vault: "凭据保险库", ssh: "SSH 加密连接", remote: "你的服务器", boundary: "凭据不进入同步数据" },
  sync: { eyebrow: "可选云同步", title: "换一台设备，\n延续你的工作方式。", description: "按需同步主机与分组清单。数据在本地加密后上传，合并前预览冲突；服务器连接仍由本地客户端建立。", cta: "了解并启用同步", chips: ["端到端加密", "冲突预览", "组织与角色"], local: "本地工作区", encrypted: "加密的主机与分组", cloud: "云端密文副本", note: "密码、私钥与终端输出不参与同步。" },
  downloads: { eyebrow: "你的下一次连接，从这里开始", title: "让远程工作，更得心应手。", description: "选择你的桌面平台，前往发布页查看可用安装包。", platforms: ["Windows", "macOS", "Linux"], packages: ["查找 Windows 的 .msi 或 .exe 安装包。", "查找与你的 Mac 芯片匹配的 .dmg 安装包。", "查找适合你的发行版的 .AppImage 或 .deb 安装包。"], cta: "查看发布版本", availability: "安装包、架构与可用版本以发布页为准。", mobile: "移动端也在路上", mobileDescription: "iOS / Android 已有自适应界面与移动私钥能力；商店下载尚未开放。", source: "查看源代码", start: "开始使用", instructions: ["安装与你的系统匹配的客户端。", "添加服务器地址与认证方式。", "核对主机指纹，开启第一段 SSH 会话。"] },
  faq: { eyebrow: "开始之前", title: "你可能还想了解", items: [
    { question: "必须注册账号才能使用吗？", answer: "不需要。主机管理、SSH 与本地工作区采用 Local-first 设计。只有选择云同步等账号服务时，才需要登录。" },
    { question: "服务器需要安装额外软件吗？", answer: "SSH、SFTP 与基础监控通过已有 SSH 服务工作，无需额外安装 Runory Agent。Docker、PM2、Nginx 等操作需要服务器本身具备对应服务与权限。" },
    { question: "AI 会自动在服务器上执行命令吗？", answer: "不会。每条命令都需要先原样展示，再由你选择 Run 或 Cancel。写入或未知命令之后，还需要单独审批只读验证命令。AI 能力需要在客户端完成相应模型配置。" },
    { question: "云端会保存我的密码和私钥吗？", answer: "不会。可选同步只上传本地加密的主机与分组清单。密码、Passphrase、私钥和终端输出不进入同步载荷，网页也不会解密服务器清单。" },
    { question: "所有平台都可以下载了吗？", answer: "Runory 采用桌面优先的发布方式。Windows、macOS 和 Linux 的安装包以发布页实际提供的版本为准。移动端已建立产品与共享核心基础，暂未提供应用商店下载。" },
  ] },
  footer: { tagline: "从任何地方，掌握你的基础设施。", product: "探索产品", resources: "开始使用", account: "账号与同步", top: "返回顶部", copyright: "Runory. 为清晰、可控的远程工作而造。" },
};

// Both locales must expose the same content shape, including every interactive label.
type TranslationShape<T> = T extends string ? string : T extends readonly (infer U)[] ? TranslationShape<U>[] : { [K in keyof T]: TranslationShape<T[K]> };
const en: TranslationShape<typeof zh> = {
  meta: { title: "Runory — Your servers. Under control.", description: "SSH, files, services, deployments and AI with per-command approval, in one local-first infrastructure workspace. Explore the Runory desktop client." },
  nav: { label: "Main navigation", product: "Product", workflow: "AI collaboration", security: "Security", pricing: "Pricing", faq: "FAQ", signIn: "Sign in", download: "Get Runory", menu: "Open navigation", close: "Close navigation", language: "中文", skip: "Skip to content" },
  hero: { badge: "Built for the people behind the servers", title: "Your servers.", accent: "Under control.", description: "From your first SSH command to files, services and deployments.\nBring every step of remote work into one focused workspace.", primary: "Get Runory", secondary: "Explore the workspace", note: "Local-first", note2: "Connect without an account", note3: "Every AI command is your call" },
  demo: { label: "Interactive workspace tour", caption: "Interactive demo · Sample data, no live server connection", sidebar: "Servers", group: "Production", connected: "Connected", secure: "Encrypted SSH connection", tabs: ["Terminal", "Files", "Monitor", "Deploy"], detail: "Session details", host: "Host", auth: "Authentication", key: "Private key", session: "Connection", files: "Remote files", name: "Name", size: "Size", modified: "Modified", queue: "Transfer queue", transferred: "Transfer complete", dashboard: "Server overview", agentless: "Collected over SSH. No monitoring agent required.", metrics: ["CPU usage", "Memory usage", "Disk usage"], services: "Service status", running: "Running", deployments: "Deployment history", deploymentName: "API application", deployed: "Deployed", deploymentSteps: ["Pull code", "Check environment", "Build application", "Start service"], deployNote: "See the stages and results of each deployment to find issues faster.", hint: "Switch tabs to explore different ways to work within one connection.", context: "Your connection, files and context. All together." },
  strip: { title: "Familiar tools. One connected experience.", items: ["SSH / SFTP", "Docker / PM2", "Nginx / SSL", "Git / Cron", "Windows / macOS / Linux"] },
  features: { eyebrow: "ONE WORKSPACE, THROUGHOUT YOUR DAY", title: "Less switching.\nMore getting things done.", description: "Keep the context you need right beside your terminal.", items: [
    { title: "A place for every connection", description: "Organize hosts into groups, search quickly and switch with ease. Keep production, staging and development in their own SSH tabs.", tags: ["Host groups", "Multiple sessions", "Key authentication"] },
    { title: "Files beside your terminal", description: "Browse remote directories, upload, download and manage files. Follow transfers in a clear queue without opening another client.", tags: ["SFTP", "Directory navigation", "Transfer queue"] },
    { title: "Know how your servers are doing", description: "Review CPU, memory and disk usage, then investigate services and logs. Work over SSH without deploying another agent.", tags: ["Dashboard", "Service status", "Log viewer"] },
    { title: "Your services, together", description: "Bring everyday Docker, PM2 and Nginx operations into one place. Understand the current state before confirming your next action.", tags: ["Docker", "PM2", "Nginx"] },
    { title: "From code to running service", description: "Organize Git deployments, environment variables, SSL, backups and scheduled jobs. Keep a history of what happened at each release.", tags: ["Git deployment", "SSL", "Backups / Cron"] },
    { title: "Make yourself at home", description: "Keep familiar terminal input, search, copy and paste. English and Chinese, light and dark themes: a workspace that fits your habits.", tags: ["English / 中文", "Light & dark", "Terminal search"] },
  ] },
  agent: { eyebrow: "AI COLLABORATION, YOUR CONTROL", title: "Find answers together.\nApprove every step.", description: "Describe the problem, review the suggestion and approve the next command. AI uses real results to continue investigating, with evidence and clear boundaries.", points: ["Review the exact command and its risk before execution", "Choose Run or Cancel for every command", "Verify the result after writes before finishing"], label: "Illustration of the AI workflow", question: "Help me check why Nginx is not responding", steps: ["Suggest", "Approve", "Review"], summaries: ["Start by checking the Nginx service status to gather evidence.", "Approve this read-only command in the client before the terminal runs it.", "AI reviews the sanitized result and proposes the next command for approval if needed."], command: "systemctl status nginx --no-pager", risk: "Read-only · Awaiting your approval", result: "Result → Analysis → Next suggestion", note: "Workflow illustration only. No commands are executed here.", runtime: "You lead. AI helps investigate." },
  security: { eyebrow: "TRUST, WITH CLEAR BOUNDARIES", title: "Connect to your servers.\nKeep hold of your data.", description: "Local-first from the start. Credentials, connections and permissions each have a clear home.", items: [
    { title: "Credentials stay in your local vault", description: "The Credential Vault manages passwords, passphrases and private keys. They never enter host profiles or cloud sync." },
    { title: "Every connection deserves a check", description: "Unknown hosts need your explicit trust. A changed host key blocks the connection." },
    { title: "Operations you can review", description: "Approve AI commands before execution. Structured repairs use change sets and verification, with real rollback only where supported." },
  ], local: "Your device", vault: "Credential Vault", ssh: "Encrypted SSH", remote: "Your server", boundary: "Credentials stay out of sync data" },
  sync: { eyebrow: "OPTIONAL CLOUD SYNC", title: "Another device.\nThe same way of working.", description: "Sync your host and group inventory when you need it. Encrypt before uploading and preview conflicts before merging. Your local client still makes every server connection.", cta: "Explore and enable sync", chips: ["End-to-end encryption", "Conflict previews", "Organizations & roles"], local: "Local workspace", encrypted: "Encrypted hosts & groups", cloud: "Encrypted cloud copy", note: "Passwords, private keys and terminal output are never synced." },
  downloads: { eyebrow: "YOUR NEXT CONNECTION STARTS HERE", title: "Make remote work feel closer.", description: "Choose your desktop platform and explore the available release packages.", platforms: ["Windows", "macOS", "Linux"], packages: ["Look for a Windows .msi or .exe installer.", "Look for a .dmg installer matching your Mac chip.", "Look for an .AppImage or .deb package for your distribution."], cta: "View releases", availability: "Available packages, architectures and versions are listed on the release page.", mobile: "Mobile is on the way, too", mobileDescription: "Adaptive iOS / Android interfaces and mobile key support are implemented. App store downloads are not yet available.", source: "Browse source", start: "Getting started", instructions: ["Install the client that matches your system.", "Add your server address and authentication method.", "Verify the host fingerprint and start your first SSH session."] },
  faq: { eyebrow: "BEFORE YOU CONNECT", title: "A few things you might be wondering", items: [
    { question: "Do I need an account?", answer: "No. Host management, SSH and your local workspace are local-first. Sign in only when you choose account services such as cloud sync." },
    { question: "Do I need to install anything on my server?", answer: "SSH, SFTP and basic monitoring use your existing SSH service. No Runory agent is needed. Docker, PM2 and Nginx operations require the corresponding software and permissions on your server." },
    { question: "Will AI run commands automatically?", answer: "No. Every command is shown exactly before you choose Run or Cancel. Writes and unknown commands need a separately approved read-only verification. AI also requires the appropriate model configuration in the client." },
    { question: "Does the cloud store my passwords or private keys?", answer: "No. Optional sync uploads only locally encrypted host and group inventories. Passwords, passphrases, private keys and terminal output stay out of sync payloads. The website does not decrypt your server inventory." },
    { question: "Can I download it on every platform?", answer: "Runory ships desktop first. Check the release page for the Windows, macOS and Linux packages actually available. Mobile interfaces and a shared core are in place, but app store downloads are not available yet." },
  ] },
  footer: { tagline: "Run your infrastructure from anywhere.", product: "Explore", resources: "Get started", account: "Account & sync", top: "Back to top", copyright: "Runory. Built for clear, controlled remote work." },
};

export type LandingCopy = TranslationShape<typeof zh>;
export function getLandingCopy(locale: Locale): LandingCopy { return locale === "zh-CN" ? zh : en; }
