import { invoke } from "@tauri-apps/api/core";
import type { ChangeSet, ChangeStepDraft, EffectiveAgentPolicy, ExecutionStrategy, FailurePolicy, FleetChangeSet, Incident, IncidentAuditExport, IncidentRequest, McpServerConfig, ModelConfigureRequest, ModelProviderStatus, Skill } from "../../types/agentic";

export const getAgentModel = () => invoke<ModelProviderStatus>("agent_model_get");
export const configureAgentModel = (request: ModelConfigureRequest) => invoke<ModelProviderStatus>("agent_model_configure", { request });
export const clearAgentModelApiKey = () => invoke<ModelProviderStatus>("agent_model_clear_api_key");
export const testAgentModel = () => invoke<void>("agent_model_test");
export const draftChangeSet = (agentRunId: string, sessionId: string, title: string, steps: ChangeStepDraft[]) => invoke<ChangeSet>("agent_changeset_draft", { request: { agentRunId, sessionId, title, steps } });
export const draftFleetChangeSet = (request: { agentRunId: string; title: string; targets: { agentRunId: string; sessionId: string; title: string; steps: ChangeStepDraft[] }[]; executionStrategy: ExecutionStrategy; failurePolicy: FailurePolicy; batchSize: number; canaryCount: number; production: boolean; serviceVerification: string | null; crossTargetVerification: boolean }) => invoke<FleetChangeSet>("agent_multi_changeset_draft", { request });
export const listFleetChangeSets = () => invoke<FleetChangeSet[]>("agent_fleet_changeset_list");
export const approveFleetChangeSet = (fleetId: string, version: number, exactTargetIds: string[]) => invoke<FleetChangeSet>("agent_fleet_changeset_approve", { fleetId, version, exactTargetIds });
export const executeFleetChangeSet = (fleetId: string, version: number) => invoke<FleetChangeSet>("agent_fleet_changeset_execute", { fleetId, version });
export const listChangeSets = () => invoke<ChangeSet[]>("agent_changeset_list");
export const getChangeSet = (changeSetId: string) => invoke<ChangeSet>("agent_changeset_get", { changeSetId });
export const approveChangeSet = (changeSetId: string, version: number) => invoke<ChangeSet>("agent_changeset_approve", { changeSetId, version });
export const approveChangeSetStep = (changeSetId: string, version: number, stepId: string) => invoke<ChangeSet>("agent_changeset_approve_step", { changeSetId, version, stepId });
export const rejectChangeSet = (changeSetId: string, version: number) => invoke<ChangeSet>("agent_changeset_reject", { changeSetId, version });
export const executeChangeSet = (changeSetId: string, version: number) => invoke<ChangeSet>("agent_changeset_execute", { changeSetId, version });
export const rollbackChangeSet = (changeSetId: string, version: number) => invoke<ChangeSet>("agent_changeset_rollback", { changeSetId, version });
export const getEffectiveAgentPolicy = (serverId: string, groupId: string | null, environment: string | null) => invoke<EffectiveAgentPolicy>("agent_policy_effective", { serverId, groupId, environment });
export const refreshSkills = () => invoke<Skill[]>("agent_skills_refresh");
export const setSkillEnabled = (skillId: string, enabled: boolean) => invoke<Skill>("agent_skill_set_enabled", { skillId, enabled });
export const listMcp = () => invoke<McpServerConfig[]>("agent_mcp_list");
export const configureMcp = (id: string, label: string, endpoint: string, token: string | null) => invoke<McpServerConfig>("agent_mcp_configure", { request: { id, label, endpoint, token } });
export const setMcpToolEnabled = (serverId: string, toolName: string, enabled: boolean) => invoke<McpServerConfig>("agent_mcp_set_tool_enabled", { serverId, toolName, enabled });
export const setMcpEnabled = (serverId: string, enabled: boolean) => invoke<McpServerConfig>("agent_mcp_set_enabled", { serverId, enabled });
export const removeMcp = (serverId: string) => invoke<void>("agent_mcp_remove", { serverId });
export const runIncident = (request: IncidentRequest) => invoke<Incident>("agent_incident_run", { request });
export const listIncidents = () => invoke<Incident[]>("agent_incident_list");
export const attachIncidentChangeSet = (incidentId: string, link: { kind: "single" | "fleet"; id: string; version: number; exactTargetIds: string[] }) => invoke<Incident>("agent_incident_attach_changeset", { incidentId, link });
export const refreshIncident = (incidentId: string) => invoke<Incident>("agent_incident_refresh", { incidentId });
export const handoffIncident = (incidentId: string, owner: string, summary: string) => invoke<Incident>("agent_incident_handoff", { incidentId, request: { owner, summary } });
export const closeIncident = (incidentId: string, code: "resolved" | "accepted-risk" | "false-positive", summary: string) => invoke<Incident>("agent_incident_close", { incidentId, request: { code, summary } });
export const exportIncident = (incidentId: string) => invoke<IncidentAuditExport>("agent_incident_export", { incidentId });
