import { invoke } from "@tauri-apps/api/core";
import type { ModelProfile } from "../../types/agentic";
export const getAgentModelProfiles = () => invoke<ModelProfile[]>("agent_model_profiles");
export const saveAgentModelProfile = (id: string | null, request: ModelConfigureRequest) => invoke<ModelProfile[]>("agent_model_profile_save", { id, request });
export const activateAgentModelProfile = (id: string) => invoke<ModelProfile[]>("agent_model_profile_activate", { id });
export const removeAgentModelProfile = (id: string) => invoke<ModelProfile[]>("agent_model_profile_remove", { id });
import type { EffectiveAgentPolicy, Incident, IncidentAuditExport, IncidentRequest, McpServerConfig, ModelConfigureRequest, ModelProviderStatus, OauthProvider, Skill } from "../../types/agentic";

export const getAgentModel = () => invoke<ModelProviderStatus>("agent_model_get");
export const configureAgentModel = (request: ModelConfigureRequest) => invoke<ModelProviderStatus>("agent_model_configure", { request });
export const clearAgentModelApiKey = () => invoke<ModelProviderStatus>("agent_model_clear_api_key");
export const testAgentModel = () => invoke<void>("agent_model_test");
export const startAgentModelOauth = (provider: OauthProvider) => invoke<ModelProviderStatus>("agent_model_oauth_start", { provider });
export const cancelAgentModelOauth = () => invoke<void>("agent_model_oauth_cancel");
export const disconnectAgentModel = () => invoke<ModelProviderStatus>("agent_model_disconnect");
export const getEffectiveAgentPolicy = (serverId: string, groupId: string | null, environment: string | null) => invoke<EffectiveAgentPolicy>("agent_policy_effective", { serverId, groupId, environment });
export const refreshSkills = () => invoke<Skill[]>("agent_skills_refresh");
export const setSkillEnabled = (skillId: string, enabled: boolean) => invoke<Skill>("agent_skill_set_enabled", { skillId, enabled });
export const listMcp = () => invoke<McpServerConfig[]>("agent_mcp_list");
export const configureMcp = (id: string, label: string, endpoint: string, token: string | null) => invoke<McpServerConfig>("agent_mcp_configure", { request: { id, label, endpoint, token } });
export const setMcpToolEnabled = (serverId: string, toolName: string, enabled: boolean) => invoke<McpServerConfig>("agent_mcp_set_tool_enabled", { serverId, toolName, enabled });
export const setMcpEnabled = (serverId: string, enabled: boolean) => invoke<McpServerConfig>("agent_mcp_set_enabled", { serverId, enabled });
export const removeMcp = (serverId: string) => invoke<void>("agent_mcp_remove", { serverId });
export const runIncident = (request: IncidentRequest) => invoke<Incident>("agent_incident_run", { request });
export const listIncidents = () => invoke<Incident[]>("agent_incident_list");
export const getIncident = (incidentId: string) => invoke<Incident>("agent_incident_get", { incidentId });
export const attachIncidentChangeSet = (incidentId: string, link: { kind: "single" | "fleet"; id: string; version: number; exactTargetIds: string[] }) => invoke<Incident>("agent_incident_attach_changeset", { incidentId, link });
export const refreshIncident = (incidentId: string) => invoke<Incident>("agent_incident_refresh", { incidentId });
export const handoffIncident = (incidentId: string, owner: string, summary: string) => invoke<Incident>("agent_incident_handoff", { incidentId, request: { owner, summary } });
export const closeIncident = (incidentId: string, code: "resolved" | "accepted-risk" | "false-positive", summary: string) => invoke<Incident>("agent_incident_close", { incidentId, request: { code, summary } });
export const exportIncident = (incidentId: string) => invoke<IncidentAuditExport>("agent_incident_export", { incidentId });
