import { Channel, invoke } from "@tauri-apps/api/core";
import type { ConnectRequest, ConnectResponse, CredentialKind, CredentialStatus, HostVerification, KnownHost, LocalFileSelection, PrivateKeyImport, RemoteImagePreview, RemoteTextPreview, SftpDirectory, SftpMetadata, TerminalEvent, TestConnectionRequest, TestConnectionResponse, TransferEvent, TransferJob } from "../../types/session";

export const prepareHostVerification = (profileId: string) => invoke<HostVerification>("known_host_prepare", { request: { profileId } });
export const trustHost = (attemptId: string, remember: boolean) => invoke<void>("known_host_trust", { request: { attemptId, remember } });
export const cancelHostVerification = (attemptId: string) => invoke<void>("known_host_cancel", { request: { attemptId } });
export const listKnownHosts = () => invoke<KnownHost[]>("known_host_list");
export const removeKnownHost = (host: string, port: number) => invoke<void>("known_host_remove", { request: { host, port } });
function openSsh(command: "ssh_connect" | "ssh_reconnect", request: ConnectRequest, onEvent: (event: TerminalEvent) => void) { const channel = new Channel<TerminalEvent>(); channel.onmessage = onEvent; return invoke<ConnectResponse>(command, { request, onEvent: channel }); }
export const connectSsh = (request: ConnectRequest, onEvent: (event: TerminalEvent) => void) => openSsh("ssh_connect", request, onEvent);
export const reconnectSsh = (request: ConnectRequest, onEvent: (event: TerminalEvent) => void) => openSsh("ssh_reconnect", request, onEvent);
export const testSsh = (request: TestConnectionRequest) => invoke<TestConnectionResponse>("ssh_test", { request });
export const writeSsh = (sessionId: string, data: Uint8Array) => invoke<void>("ssh_write", { request: { sessionId, data: Array.from(data) } });
export const resizeSsh = (sessionId: string, cols: number, rows: number) => invoke<void>("ssh_resize", { request: { sessionId, cols, rows } });
export const disconnectSsh = (sessionId: string) => invoke<void>("ssh_disconnect", { request: { sessionId } });
export const openSftp = (sessionId: string) => invoke<SftpDirectory>("sftp_open", { request: { sessionId } });
export const listDirectory = (sessionId: string, path: string) => invoke<SftpDirectory>("list_directory", { request: { sessionId, path } });
export const statRemotePath = (sessionId: string, path: string) => invoke<SftpMetadata>("stat", { request: { sessionId, path } });
export const previewRemoteImage = (sessionId: string, path: string) => invoke<RemoteImagePreview>("sftp_preview_image", { request: { sessionId, path } });
export const previewRemoteText = (sessionId: string, path: string) => invoke<RemoteTextPreview>("sftp_preview_text", { request: { sessionId, path } });
export const changeDirectory = (sessionId: string, path: string) => invoke<SftpDirectory>("change_directory", { request: { sessionId, path } });
export const refreshDirectory = (sessionId: string) => invoke<SftpDirectory>("refresh", { request: { sessionId } });
export const createRemoteDirectory = (sessionId: string, parent: string, name: string) => invoke<SftpDirectory>("create_directory", { request: { sessionId, parent, name } });
export const renameRemoteEntry = (sessionId: string, path: string, newName: string) => invoke<SftpDirectory>("rename", { request: { sessionId, path, newName } });
export const deleteRemoteEntry = (sessionId: string, path: string, recursive: boolean) => invoke<SftpDirectory>("delete", { request: { sessionId, path, recursive } });
export const selectUploadFiles = () => invoke<LocalFileSelection[]>("sftp_select_upload_files");
export const selectDownloadTarget = (suggestedName: string) => invoke<LocalFileSelection | null>("sftp_select_download_target", { request: { suggestedName } });
export const startUpload = (sessionId: string, grantId: string, remoteDirectory: string, overwrite = false) => invoke<TransferJob>("sftp_start_upload", { request: { sessionId, grantId, remoteDirectory, overwrite } });
export const startDownload = (sessionId: string, grantId: string, remotePath: string) => invoke<TransferJob>("sftp_start_download", { request: { sessionId, grantId, remotePath } });
export const listTransfers = (sessionId: string) => invoke<TransferJob[]>("sftp_transfer_list", { request: { sessionId } });
export const subscribeTransfers = (sessionId: string, onEvent: (event: TransferEvent) => void) => { const channel = new Channel<TransferEvent>(); channel.onmessage = onEvent; return invoke<void>("sftp_transfer_subscribe", { request: { sessionId }, onEvent: channel }); };
export const cancelTransfer = (sessionId: string, jobId: string) => invoke<void>("sftp_transfer_cancel", { request: { sessionId, jobId } });
export const retryTransfer = (sessionId: string, jobId: string, overwrite = false) => invoke<TransferJob>("sftp_transfer_retry", { request: { sessionId, jobId, overwrite } });
export const unlockVault = (masterPassword: string) => invoke<void>("vault_unlock", { request: { masterPassword } });
export const lockVault = () => invoke<void>("vault_lock");
export const credentialStatus = (profileId: string | null = null, kind: CredentialKind | null = null) => invoke<CredentialStatus>("credential_status", { request: { profileId, kind } });
export const forgetCredential = (profileId: string, kind: CredentialKind) => invoke<void>("credential_forget", { request: { profileId, kind } });
export const importPrivateKey = () => invoke<PrivateKeyImport | null>("private_key_import");
export const forgetPrivateKey = (keyId: string) => invoke<void>("private_key_forget", { request: { keyId } });
