- uses: tauri-apps/tauri-action@v1
	env:
		GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

		RUNORY_UPDATER_ENDPOINT: ${{ vars.RUNORY_UPDATER_ENDPOINT }}
		RUNORY_UPDATER_PUBKEY: ${{ vars.RUNORY_UPDATER_PUBKEY }}

		TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
		TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
	with:
		tagName: v__VERSION__
		releaseName: Runory v__VERSION__
		releaseBody: See the release notes for details.
		releaseDraft: true
    		prerelease: false
    		args: --config src-tauri/tauri.release.conf.json
